env:
  TERM: xterm-256color

shell: zsh

font:
  normal:
    family: Terminus
    style: Regular
  bold:
    family: Terminus
    style: Bold
  italic:
    family: Terminus
    style: Italic
  size: 12

# Colors (Solarized Dark)
colors:
  # Default colors
  primary:
    background: '0x002B36'
    foreground: '0x839496'

  # Normal colors
  normal:
    black:   '0x073642'
    red:     '0xDC322F'
    green:   '0x859900'
    yellow:  '0xB58900'
    blue:    '0x268BD2'
    magenta: '0xD33682'
    cyan:    '0x2AA198'
    white:   '0xEEE8D5'

  # Bright colors
  bright:
    black:   '0x002B36'
    red:     '0xCB4B16'
    green:   '0x586E75'
    yellow:  '0x657B83'
    blue:    '0x839496'
    magenta: '0x6C71C4'
    cyan:    '0x93A1A1'
    white:   '0xFDF6E3'

key_bindings:
  - key: Return
    mods: Shift
    chars: "\x1b[13;2u"
  - key: Return
    mods: Control
    chars: "\x1b[13;5u"
