# Prefix
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Window split keys
bind-key v split-window -h
bind-key h split-window -v

# Config reload
bind-key r source-file ~/.tmux.conf \; display-message "tmux conf reloaded"

# Switch btn Panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Switch btn Windows
bind -n S-Left previous-window
bind -n S-Right next-window

# Initial Setup and Theme
set -g default-terminal xterm-256color
#set -g status-keys vi
set-window-option -g window-status-format '#[fg=yellow,dim]#I#[fg=yellow]:#[default]#W#[fg=grey,dim]#F'
set-window-option -g window-status-current-format '#[bg=#444444,fg=yellow,bold]#I#[bg=444444,fg=cyan]:#[fg=green]#W#[fg=dim]#F'

set-option -g message-bg blue
set-option -g message-fg green
set-option -g pane-active-border-fg green

# Status Bar
#set -g status-justify centre
set -g status-bg black
set -g status-fg green
set -g status-interval 60
set -g status-left-length 30
set -g status-left '#[fg=#00ff00][#S] '
set -g status-right '#[fg=green]%H:%M '
